### ISSUE TITLE
Documentation print(widget.get_html_code()) raises TypeError

### ISSUE THREAD

**Issue by appel268576** [paymentwall/paymentwall-python#4]
Python 2.6

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ApPeL/.virtualenvs/fundedbyme.com/src/paymentwall-python/paymentwall/widget.py", line 109, in get_html_code
    return '<iframe src="' + self.get_url() + '" ' + attributes_query + '>    </iframe>'
  File "/Users/ApPeL/.virtualenvs/fundedbyme.com/src/paymentwall-python/paymentwall/widget.py", line 92, in get_url
    params['sign'] = self.calculate_signature(params, self.get_secret_key(), int(signature_version))
  File "/Users/ApPeL/.virtualenvs/fundedbyme.com/src/paymentwall-python/paymentwall/widget.py", line 142, in calculate_signature
    base_string += secret
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by naranjia** [comment]
This happens when you forget to set your secret key with `Paymentwall.set_secret_key()`
